    name: Lint files with ruff

    on:
        ["push"]
    
    jobs:
        lint:
            runs-on: ubuntu-latest
            strategy:
                matrix:
                    python-version: [">=3.13"]
            steps:
                - uses: actions/checkout@v5

                - name: Install python v${{matrix.python-version}} and uv
                  uses: astral-sh/setup-uv@v7
                  with:
                      python-version: ${{ matrix.python-version }}

                - name: Ruff lint
                  run:  uv run ruff check . --output-format=github

                - name: Ruff check formatting
                  run:  uv run ruff format . --check --diff